# Generated by Django 4.1.5 on 2023-03-13 17:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=32)),
                ('model', models.CharField(max_length=32)),
                ('image', models.ImageField(blank=True, upload_to='cars/')),
                ('description', models.TextField(blank=True, max_length=512)),
                ('engine_type', models.CharField(choices=[('diesel', 'diesel'), ('petrol', 'petrol'), ('electric', 'electric')], default='diesel', max_length=32)),
                ('engine_capacity', models.PositiveSmallIntegerField(help_text='engine capacity in cm³')),
                ('engine_power', models.PositiveSmallIntegerField(help_text='engine power in HP')),
                ('transmission_type', models.CharField(choices=[('manual', 'manual gear'), ('automatic', 'automatic gear')], default='manual', max_length=32)),
                ('seats_no', models.PositiveSmallIntegerField(help_text='number of seats')),
                ('luggage_compartment', models.PositiveSmallIntegerField(help_text='number of bags')),
                ('is_available', models.BooleanField(default=True)),
                ('added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='standard', max_length=24, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('start_rent', models.CharField(blank=True, max_length=32)),
                ('stop_rent', models.CharField(blank=True, max_length=32)),
                ('car', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.car')),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, max_length=32)),
                ('city', models.CharField(max_length=64)),
                ('street_address', models.CharField(max_length=64)),
                ('post_code', models.CharField(max_length=10)),
                ('description', models.TextField(blank=True, max_length=512)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('manager', models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'managers'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managers_set', to=settings.AUTH_USER_MODEL, verbose_name='Manager')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.category'),
        ),
        migrations.AddField(
            model_name='car',
            name='features',
            field=models.ManyToManyField(to='cars.feature'),
        ),
    ]
